import type { Metadata } from 'next'
import './globals.css'
import localFont from "next/font/local"

const overusedGrotesk = localFont({
  src: "./OverusedGrotesk-VF.woff2",
  display: "swap",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={overusedGrotesk.className}>{children}</body>
    </html>
  )
}
